spring:
  datasource:
    url: jdbc:mysql://localhost:3306/file_upload_thymeleaf?useSSL=false&serverTimezone=UTC
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
          dialect:  org.hibernate.dialect.MySQL5Dialect

  servlet:
    multipart:
      file-size-threshold: 2KB
      enabled: true
      max-file-size: 10MB
      max-request-size: 15MB

file:
  upload-dir: ./uploads
